##默认使用配置
spring:
  #html
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
  #数据库
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootTest?characterEncoding=utf-8
    userName: root
    password: 123456789
    #jpa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: true
  #redis
  redis:
    #数据库索引
    database: 0
    #service path
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 0
        #连接池中的最小空闲连接
        min-idle: 0
    #超时
    timeout: 1000

  # spring local resource config
  resource:
    path: /upload/
    path.pattern: /upload/**
    folder:
      windows: G:/upload
      linux: /upload/


##log
#logging: ,.
#  config: classpath:config/logback.xml
#    level:
#      org:
#        hibernate:
#            SQL: DEBUG

server:
  ssl:
    key-store: classpath:.keystore
    key-password: 123456

#公共配置与profiles选择无关
#mybatis version:2.1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.home.moudle.home1.mapper

